In [ ]:
"""
Purpose: Want to verify if the intuiton about the determinant
is valid where the problem of the determinant can be turned into
an easy problem as a change of basis to orthogonal basis kind
of generated like the gram schmidt process

Determinnat: The n dimensinoal volume of what the unit vectors
get mapped to by the matrix.

0) Pick 1st vector as 1st error vector (e0) and make prod = |v|
1) Find the projection of next vector (vn) onto
linear combination of all previous error vectors (Se)
2) Find the error vector of en = vn - Se
3) Multiply current product by |en|
4) Repeat 1 - 3 until all vectors processed

Why like this interpretation:
1) Most of linear algebra is about finding a way
to reduce the problem to an easier problem
    a. most of the time reducing

2) There is a nice compliment between
    i) the dot product (which is how find the projections)
    ii) the determinant (error to the projection)
- a sort of trade off that you see in 2d where the dot product
  is the a*b*cos and the determinant is a*b*sin
"""

'\nPurpose: Want to verify if the intuiton about the determinant\nis valid where the problem of the determinant can be turned into\nan easy problem as a change of basis to orthogonal basis kind\nof generated like the gram schmidt process\n\nDeterminnat: The n dimensinoal volume of what the unit vectors\nget mapped to by the matrix. \n\n0) Pick 1st vector as 1st error vector (e0) and make prod = |v|\n1) Find the projection of next vector (vn) onto\nlinear combination of all previous error vectors (Se)\n2) Find the error vector of en = vn - Se\n3) Multiply current product by |en|\n4) Repeat 1 - 3 until all vectors processed\n\nWhy like this interpretation: \n1) Most of linear algebra is about finding a way\nto reduce the problem to an easier problem\n    a. most of the time reducing \n\n2) There is a nice compliment between \n    i) the dot product (which is how find the projections)\n    ii) the determinant (error to the projection)\n- a sort of trade off that you see in 2d where the do

In [6]:
%load_ext autoreload
%autoreload 2

In [7]:
from os import sys
from pathlib import Path
base_path = Path("/content/drive/MyDrive/Deep_Learning/torch_tools/torch_tools")
sys.path.append(str(base_path ))
sys.path.append(str(base_path / Path("linalg")))

# Calculating the Determinant

In [8]:
import numpy as np
import vector as vec

In [ ]:
vecs = np.array([
    [1,3,8],
    [2,10,3],
    [-1,2,4]
])
M = vecs.T
M

array([[ 1,  2, -1],
       [ 3, 10,  2],
       [ 8,  3,  4]])

In [ ]:
def gram_schmidt_columns(X):
    Q, R = np.linalg.qr(X)
    return Q,R

Q,R = gram_schmidt_columns(M)
Q,R

(array([[-0.30151134,  0.49236596, -0.81649658],
        [-0.30151134, -0.86164044, -0.40824829],
        [-0.90453403,  0.12309149,  0.40824829]]),
 array([[-3.31662479, -4.52267017, -7.53778361],
        [ 0.        , -0.73854895, -1.23091491],
        [ 0.        ,  0.        ,  0.81649658]]))

In [ ]:
vec.magnitude(vecs[0])

8.602325267042627

In [ ]:
det_by_hand = np.prod(np.diag(R))
det_by_np = np.linalg.det(M)

det_by_hand,det_by_np

(112.99999999999987, 113.00000000000003)

# Determine if Determinant can be understood by its projectinos

In [ ]:
import numpy as np

a = np.array([1,1,3])
b = np.array([1,2,4])
c = np.array([1,3,7])

M = np.vstack([a,b,c]).T
M

array([[1, 1, 1],
       [1, 2, 3],
       [3, 4, 7]])

In [ ]:
x,y,z = list(range(3))

def proj_area(x,y):
    return (
        a[x]*b[y] - b[x]*a[y]
    + a[x]*c[y] - c[x]*a[y]
    + b[x]*c[y] - c[x]*b[y]
    )
proj_area(0,1),proj_area(0,2),proj_area(1,2)

(4, 8, -2)

In [ ]:
Q,R = gram_schmidt_columns(M)
R

array([[-3.31662479, -4.52267017, -7.53778361],
       [ 0.        , -0.73854895, -1.23091491],
       [ 0.        ,  0.        ,  0.81649658]])

In [ ]:
diag = [R[i,i] for i in range(len(R))]
np.prod(diag)

1.999999999999999

In [ ]:
np.linalg.det(M)

1.9999999999999996

# Looking at very negative determinant

In [2]:
import numpy as np

In [3]:
v1 = np.array([1,5])
v2 = np.array([1,-4])
M = np.vstack([v1,v2]).T
M

array([[ 1,  1],
       [ 5, -4]])

In [4]:
np.linalg.det(M)

-8.999999999999998

In [10]:
# finding the area of the triangle
v1_unit = vec.unit(v1)
v2_proj = np.dot(v1_unit,v2)*v1_unit
e = v2 - v2_proj
e

array([ 1.73076923, -0.34615385])

In [11]:
tri_magn = vec.magn(v1)*vec.magn(e)
tri_magn

9.0