In [1]:
import numpy as np

In [2]:
A = np.array([
    [1,7],
    [4,3]
])

B = np.array([
    [8,1],
    [2,5]
])

C = A@B
C

array([[22, 36],
       [38, 19]])

In [3]:
np.dot(C[:,0],C[:,1])

1514

In [4]:
22*36 + 38*19

1514

# dot product in stages

In [5]:
(8*17*1) + \
(2 * 58*5 ) + \
(8*19*5) + \
(2*19*1)

1514

# Looking if inverse path is correct

In [43]:
import numpy as np
M = np.array([
    [1,4,5],
    [2,10,8],
    [5,6,12]
])

ax,ay,az = M[:,0]
bx,by,bz = M[:,1]
cx,cy,cz = M[:,2]

byr = by - ay/ax*bx
bzr = bz - az/ax*bx
cyr = cy - ay/ax*cx
czr = cz - cyr*bzr/byr - cx*az/ax



U_non_norm = np.array([
    [ax,bx,cx],
    [0,byr,cyr],
    [0,0,czr],
])

L = np.array([
    [1,0,0],
    [ay/ax,1,0],
    [az/ax,bzr/byr,1]
])

U = np.array([
    [1,bx/byr,cx/czr],
    [0,1,cyr/czr],
    [0,0,1]
])

D = np.diag([ax,byr,czr])
result = (L@U@D)#.astype('int')
display(result,M)
np.array_equal(result,M)
result - M

array([[ 1.,  4.,  5.],
       [ 2., 10.,  8.],
       [ 5.,  6., 12.]])

array([[ 1,  4,  5],
       [ 2, 10,  8],
       [ 5,  6, 12]])

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -7.10542736e-15]])

In [ ]:
# showing how to manually get the inverses

In [49]:
L_inv = np.array([
    [1,0,0],
    [-ay/ax,1,0],
    [-az/ax + (-bzr/byr)*(-ay/ax),-bzr/byr,1]
])

L_inv_2_step = np.array([
    [1,0,0],
    [0,1,0],
    [0,-bzr/byr,1]
])@np.array([
    [1,0,0],
    [-ay/ax,1,0],
    [-az/ax,0,1]
])

display(L@L_inv)
display(L@L_inv_2_step)

U_inv = np.array([
    [1, -bx/byr, -cx/czr + bx/byr*cyr/czr],
    [0,1,-cyr/czr],
    [0,0,1]
])

U_inv_2_step = np.array([
    [1,-bx/byr,0,],
     [0,1,0,],
    [0,0,1]
]) @ np.array([
    [1,0,-cx/czr],
    [0,1,-cyr/czr],
    [0,0,1]
])

display(U@U_inv)
display(U@U_inv_2_step)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
L

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  0.],
       [ 5., -7.,  1.]])

In [13]:
np.linalg.inv(L)

array([[ 1.00000000e+00,  1.77635684e-16,  3.50596745e-18],
       [-2.00000000e+00,  1.00000000e+00, -2.92163954e-17],
       [-1.90000000e+01,  7.00000000e+00,  1.00000000e+00]])

In [7]:
M_inv = np.linalg.inv(M)
display(np.round(M@M_inv,2))

M_inv

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [-0., -0.,  1.]])

array([[-1.33333333,  0.33333333,  0.33333333],
       [-0.2962963 ,  0.24074074, -0.03703704],
       [ 0.7037037 , -0.25925926, -0.03703704]])

## checking to see if manual calculation of inverse is correct

In [36]:
axn_list = [
    1/ax,
    1/ax*(-bx)*(1/byr)*(-ay/ax),
    1/ax*(-bx)*(1/byr)*(-cyr)*(1/czr)*(-bzr/byr)*(-ay/ax),
    1/ax*(-bx)*(1/byr)*(-cyr)*(1/czr)*(-az/ax),
    1/ax*(-cx)*(1/czr)*(-az/ax),
    1/ax*(-cx)*(1/czr)*(-bzr/byr)*(-ay/ax),
]
display(axn_list)
axn = np.sum(axn_list)
axn,M_inv[0,0]

[1.0,
 4.0,
 -2.074074074074074,
 -0.7407407407407407,
 -0.9259259259259258,
 -2.5925925925925926]

(-1.3333333333333333, -1.3333333333333337)

### checking cyn

In [32]:
byn = [
    1/czr*(-bzr/byr)
]
byn

[-0.25925925925925924]

In [33]:
cynl = [
    1/byr*(-cyr)*1/czr
]
cyn = np.sum(cynl)
cyn

-0.037037037037037035

In [34]:
aynl = [
    1/byr*(-ay/ax),
    1/byr*(-cyr)*1/czr*(-bzr/byr)*(-ay/ax),
    1/byr*(-cyr)*1/czr*(-az/ax)
]
ayn = np.sum(aynl)
ayn

-0.29629629629629634

In [35]:
bxnl = [
    1/ax*(-bx)*(1/byr),
    1/ax*(-bx)*(1/byr)*(-cyr)*(1/czr)*(-bzr/byr),
    1/ax*(-cx)*(1/czr)*(-bzr/byr),
]
bxn = np.sum(bxnl)
bxn


0.33333333333333326

In [29]:
M_inv

array([[-1.33333333,  0.33333333,  0.33333333],
       [-0.2962963 ,  0.24074074, -0.03703704],
       [ 0.7037037 , -0.25925926, -0.03703704]])

In [38]:
aynl = [
    1/byr*(-ay/ax),
    1/byr*(-cyr)*1/czr*(-bzr/byr)*(-ay/ax),
    1/byr*(-cyr)*1/czr*(-az/ax)
]

np.sum(aynl)

-0.29629629629629634

In [39]:
det = ax*byr*czr

1/(det)*(-ay*czr - cyr*bzr*ay/byr + az*cyr)

-0.2962962962962963