In [1]:
"""
Purpose: want to test and create a method of interpreting
the determinant calculation as the error projections
where only the standard basis can be used for the errors
"""

'\nPurpose: want to test and create a method of interpreting\nthe determinant calculation as the error projections\nwhere only the standard basis can be used for the errors\n'

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from os import sys
from pathlib import Path
base_path = Path("/content/drive/MyDrive/Deep_Learning/torch_tools/torch_tools")
sys.path.append(str(base_path ))
sys.path.append(str(base_path / Path("linalg")))

# Calculating the determinant of 2 3D vectors

In [3]:
import numpy as np
import vector as vec

In [ ]:
M = np.array([
    [1,4,5],
    [2,10,3],
    [-2,4,5]
])

r_magns = np.array([vec.magn(k) for k in M])
R = np.diag(r_magns)
Rinv = np.diag(1/r_magns)

c_magns = np.array([vec.magn(k) for k in M.T])
C = np.diag(c_magns)
Cinv = np.diag(1/c_magns)


In [ ]:
Mh = Rinv @ M @ Cinv
Mh

array([[ 0.05143445,  0.05372153,  0.10044293],
       [ 0.06271472,  0.08187924,  0.03674143],
       [-0.0993808 ,  0.05189993,  0.09703708]])

In [ ]:
R @ Mh @ C

array([[ 1.,  4.,  5.],
       [ 2., 10.,  3.],
       [-2.,  4.,  5.]])

In [ ]:
R

array([[ 6.4807407 ,  0.        ,  0.        ],
       [ 0.        , 10.63014581,  0.        ],
       [ 0.        ,  0.        ,  6.70820393]])

In [ ]:
C

array([[ 3.        ,  0.        ,  0.        ],
       [ 0.        , 11.48912529,  0.        ],
       [ 0.        ,  0.        ,  7.68114575]])

In [ ]:
vec.unit([1,4,5])/3

array([0.05143445, 0.2057378 , 0.25717225])

# testing the rref

In [ ]:
M = np.array([
    [1,2,3],
    [2,4,7],
    [4,8,12]
])

In [ ]:
A = np.array([
    [1,0,0],
    [2,1,0],
    [4,0,1],
])

B = np.array([
    [1,3,0],
    [0,1,0,],
    [0,0,1],
])

rref = np.array([
    [1,2,0],
    [0,0,1],
    [0,0,0]
])

A@B@rref

array([[ 1,  2,  3],
       [ 2,  4,  7],
       [ 4,  8, 12]])

# Testing that the row rref interpretation is correct

In [14]:
M = np.array([
    [2,4,12],
    [4,14,18],
    [6,18,22]
])

a1 = np.array([
    [1,0,0],
    [2,1,0],
    [3,0,1]
])

# the matrix after factoring out a1
b1 = np.array([
    [2,4,12],
    [0,6,-6],
    [0,6,-14]
])

a2 = np.array([
    [1,0,0],
    [0,1,0],
    [0,1,1]
])

# the matrix after factoring out a1 and a2
b2 = np.array([
    [2,4,12],
    [0,6,-6],
    [0,0,-8]
])

display(a1@a2@b2)

array([[ 2,  4, 12],
       [ 4, 14, 18],
       [ 6, 18, 22]])

In [13]:
# note: in this case the rows beforehand can just be combined
display(a1@a2)

array([[1, 0, 0],
       [2, 1, 0],
       [3, 1, 1]])

In [15]:
# what a row swap looks like
a3 = np.array([
    [1,0,0],
    [0,0,1],
    [0,1,0]
])

a3@M

array([[ 2,  4, 12],
       [ 6, 18, 22],
       [ 4, 14, 18]])

In [17]:
A = np.array([
    [1,0,0],
    [4,1,0],
    [9,0,1]
])

B = np.array([
    [1,0,0],
    [0,1,0],
    [0,2,1]
])

C = np.array([
    [1,0,2],
    [0,1,3],
    [0,0,1]
])

A@B@C

array([[ 1,  0,  2],
       [ 4,  1, 11],
       [ 9,  2, 25]])

# how the reduced row echelon solves linear system of equations

In [ ]:
"""
Process:
1) Perform reduction to upper triangle by factoring out the lower triangle
- factor out the same matrix from the column
2) once it's an identity matrix then gives the answer?

"""

# Determinant from paths

In [4]:
ax,ay,az = 4,9,17
bx,by,bz = 13,11,-3
cx,cy,cz = -3,1,18

M = np.array([
    [ax,ay,az],
    [bx,by,bz],
    [cx,cy,cz]
])

M

array([[ 4,  9, 17],
       [13, 11, -3],
       [-3,  1, 18]])

In [5]:
B = np.array([
    [1,0,0],
    [bx/ax,1,0],
    [cx/ax,(cy-ay*cx/ax)/(by - bx/ax*ay),1],
])
B

array([[ 1.        ,  0.        ,  0.        ],
       [ 3.25      ,  1.        ,  0.        ],
       [-0.75      , -0.42465753,  1.        ]])

In [6]:
Binv = np.linalg.inv(B)
Binv

array([[ 1.        ,  0.        ,  0.        ],
       [-3.25      ,  1.        , -0.        ],
       [-0.63013699,  0.42465753,  1.        ]])

In [7]:
ref = Binv@M
ref[np.where(np.abs(ref) < 0.000001)] = 0
ref

array([[  4.        ,   9.        ,  17.        ],
       [  0.        , -18.25      , -58.25      ],
       [  0.        ,   0.        ,   6.01369863]])

In [46]:
np.linalg.det(M)

-439.00000000000006

In [40]:
np.prod(np.diag(ref))

-439.0000000000002

In [8]:
m1 = ax
m2 = by - (bx/ax)*ay
m3 = cz - (cx/ax)*az - (cy - (cx/ax)*ay )/(by - (bx/ax)*ay)*(bz-(bx/ax)*az)
m1*m2*m3

-439.0

In [11]:
byn = by - bx/ax*ay
bzn = bz - bx/ax*az

czn = [
    cz,
    cy*(-1/byn)*bzn,
    cx*(-1/ax)*az,
    cx*(-1/ax)*ay*(-1/byn)*bzn,

]



np.sum(my_list)

6.013698630136986

# Trying with 4D

In [36]:
aw = 10
bw = -5
cw = 15
dx,dy,dz,dw = -6,12,5,17

Md = np.array([
    [ax,ay,az,aw],
    [bx,by,bz,bw,],
    [cx,cy,cz,cw],
    [dx,dy,dz,dw],
])

Md

array([[ 4,  9, 17, 10],
       [13, 11, -3, -5],
       [-3,  1, 18, 15],
       [-6, 12,  5, 17]])

In [38]:
Md

array([[ 4,  9, 17, 10],
       [13, 11, -3, -5],
       [-3,  1, 18, 15],
       [-6, 12,  5, 17]])

In [51]:
byn_list = [
    by,
    bx*(-1/ax)*ay,
]
byn = np.sum(byn_list)

bzn_list = [
    bz,
    bx*(-1/ax)*az,
]
bzn = np.sum(bzn_list)

bwn_list = [
    bw,
    bx*(-1/ax)*aw,
]
bwn = np.sum(bwn_list)

czn_list = [
    cz,
    cy*(-1/byn)*bzn,
    cx*(-1/ax)*az,
    cx*(-1/ax)*ay*(-1/byn)*bzn,

]

czn = np.sum(czn_list)

cwn_list = [
    cw,
    cx*(-1/ax)*aw,

    cy*(-1/byn)*bwn,

    cx*(-1/ax)*ay*(-1/byn)*bwn,

]
cwn = np.sum(cwn_list)

dw_list = [
    # # same as previous steps:
    dw,
    dx*(-1/ax)*aw,

    dx*(-1/ax)*ay*(-1/byn)*bwn,
    dy*(-1/byn)*bwn,

    # # new steps for z elimination
]

# dw_list =[
#     dx*(-1/ax)*ay*(-1/byn)*bzn*(-1/czn)*cwn,
#     dx*(-1/ax)*az*(-1/czn)*cwn,
#     dx*(-1/ax)*ay*(-1/byn)*bwn,
#     dz*(-1/ax)*aw,

#     dy*(-1/byn)*bzn*(-1/czn)*cwn,
#     dy*(-1/byn)*bwn,

#     dz*(-1/czn)*cwn,

#     dw

# ]

dw_new = np.sum(dw_list)
np.linalg.det(Md),ax*byn*czn*dw_new

(-15472.999999999978, 8954.39726027397)

In [65]:
dzn

-97.64041095890411

In [74]:
czn_list = [
    cz,
    cy*(-1/byn)*bzn,
    cx*(-1/ax)*az,
    cx*(-1/ax)*ay*(-1/byn)*bzn,

]
czn = np.sum(czn_list)

cwn_list = [
    cw,
    cx*(-1/ax)*aw,

    cy*(-1/byn)*bwn,

    cx*(-1/ax)*ay*(-1/byn)*bwn,

]
cwn = np.sum(cwn_list)

dzn_list = [
    dz,
    dx*(-1/ax)*az,
    -1*((dy - dx/ax*ay)/(by - bx/ax*ay)*(bz - bx/ax*az))
]

dw_list = [
    # # same as previous steps:
    dw,
    dx*(-1/ax)*aw,

    dx*(-1/ax)*ay*(-1/byn)*bwn,
    dy*(-1/byn)*bwn,

]

#previous dz path (just like cz but with different indexes, and then added extra step
# all the combinations involving the c step (aka, all the steps involving the node before it)
dzn_list = [
    dz*(-1/czn)*cwn,
    dy*(-1/byn)*bzn*(-1/czn)*cwn,
    dx*(-1/ax)*az*(-1/czn)*cwn,
    dx*(-1/ax)*ay*(-1/byn)*bzn*(-1/czn)*cwn,

]
dzn = np.sum(dzn_list)

dw_check = np.sum(dw_list) - np.sum(dzn)/czn * cwn
dw_check = np.sum(dw_list) + np.sum(dzn)
dw_check

35.24601366742599

In [75]:
"""
Conclusion: each step creates all the combinations involving
the row right above it

should be 2^(n-1) paths [ -1 because always starting and ending with bottom]
to simplify on a "no upward" path simplified graph
"""

'\nConclusion: each step creates all the combinations involving \nthe row right above it\n'

In [77]:
# should be 2
dzn_scratch = [
    dw,# 0 0 0
    dz*(-1/czn)*cwn,# 0 0 1
    dy*(-1/byn)*bwn,# 0 1 0
    dy*(-1/byn)*bzn*(-1/czn)*cwn,# 0 1 1
    dx*(-1/ax)*aw,# 1 0 0
    dx*(-1/ax)*az*(-1/czn)*cwn,# 1 0 1
    dx*(-1/ax)*ay*(-1/byn)*bwn,# 1 1 0
    dx*(-1/ax)*ay*(-1/byn)*bzn*(-1/czn)*cwn,#1 1 1
]
np.sum(dzn_scratch)

35.246013667426

In [54]:
np.linalg.det(Md)/np.linalg.det(M)

35.24601366742591

In [48]:
import numpy as np

def generate_binary_combinations(n):
    # Generate all binary combinations of length n
    num_combinations = 2 ** n
    binary_combinations = np.array([list(np.binary_repr(i, width=n)) for i in range(num_combinations)])
    # Convert to integer type
    binary_matrix = binary_combinations.astype(int)
    return binary_matrix

# Example usage
n = len(dw_list)  # Length of binary numbers
binary_matrix = generate_binary_combinations(n)
print(binary_matrix)

#binary_matrix @ np.array(dw_list).reshape(-1,1)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 ...
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]


In [58]:
cwn_check = [
    dz,
    dx*(-1/ax)*az,
    -1*((cy - cx/ax*ay)/(by-bx/ax*(ay)))*(dz - bx/ax*az)
]

np.sum(cwn_check),cwn

(9.160958904109592, 6.575342465753428)

In [43]:
cwn_check = [
    cw,
    cx*(-1/ax)*aw,
    -1*((cy - cx/ax*ay)/(by-bx/ax*(ay)))*(bw - bx/ax*aw)
]

np.sum(cwn_check),cwn

(6.575342465753426, 6.575342465753428)

In [32]:
czn

6.013698630136986

In [29]:
import scipy
scipy.linalg.lu(Md)

(array([[0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-0.46153846,  1.        ,  0.        ,  0.        ],
        [ 0.30769231,  0.32882883,  1.        ,  0.        ],
        [-0.23076923,  0.20720721,  0.98950202,  1.        ]]),
 array([[13.        , 11.        , -3.        , -5.        ],
        [ 0.        , 17.07692308,  3.61538462, 14.69230769],
        [ 0.        ,  0.        , 16.73423423,  6.70720721],
        [ 0.        ,  0.        ,  0.        ,  4.16500673]]))

In [31]:
ax

4

In [30]:
np.linalg.det(Md)/np.linalg.det(M)

35.24601366742591

In [20]:
byn

-457.0

In [17]:
np.linalg.det(M[:2,:2])

-72.99999999999999

In [58]:
cz, (cx/ax)*az, (cy - (cx/ax)*ay )/(by - (bx/ax)*ay)*(bz-(bx/ax)*az)

(18, -12.75, 24.736301369863014)

In [64]:
cz, (cx/ax)*az, (cy/by)*bz, (cx/bx)*bz, (cx*ay)/(ax*by)*bz

(18, -12.75, -0.2727272727272727, 0.6923076923076923, 1.8409090909090908)

In [77]:
by_new = by - bx/ax*ay
bz_new = bz - bx/ax*az

value = cz + cy*(-1/by_new)*bz_new + cx*(-1/ax)*az + cx*(-1/ax)*ay*(-1/by_new)*bz_new
print(value)
cz + cx/(-ax)*ay/(-by_new)*bz_new + cx/(-ax)*az + cy/(-1*by_new)*bz_new

6.013698630136986


6.013698630136988

In [98]:
cy*(-1/by_new)*bz_new, cy*(-1/(by - bx/ax*ay))*bz_new,cy*(-1/by)*bz_new + cy*(-1/(bx/ax*ay))*bz_new

(-3.191780821917808, -3.191780821917808, 7.286907536907537)

In [85]:
np.sum([cy*(-1/by)*bz,cy*(-1/by_alt)*bz,cy*(-1/by)*bz_alt,cy*(-1/by_alt)*bz_alt,])

-88.00503907856849

In [84]:
cx*(-1/ax)*ay*(-1/by)*bz,cx*(-1/ax)*ay*(-1/by_alt)*bz,cx*(-1/ax)*ay*(-1/by)*bz_alt,cx*(-1/ax)*ay*(-1/by_alt)*bz_alt,

(1.8409090909090908,
 -592.3124999999999,
 0.011106540518305225,
 -3.5735294117647056)

In [94]:
by_new,by,bx/ax*ay,(ay)*(-1/ax)*(bx),by_alt

(-18.25, 11, 29.25, -29.25, -29.25)

In [95]:
by_alt = (ay)*(-1/ax)*(bx)
bz_alt = (az)*(-1/ax)*(bx)

loops = [
    cz,

    cx*(-1/ax)*az,

    #cy*(-1/by_new)*bz_new,
    cy*(-1/by)*bz,
    -1*cy*(-1/by_alt)*bz,
    -1*cy*(-1/by)*bz_alt,
    cy*(-1/by_alt)*bz_alt,

    #cx*(-1/ax)*ay*(-1/by_new)*bz_new
    cx*(-1/ax)*ay*(-1/by)*bz,
    -1*cx*(-1/ax)*ay*(-1/by_alt)*bz,
    -1*cx*(-1/ax)*ay*(-1/by)*bz_alt,
    cx*(-1/ax)*ay*(-1/by_alt)*bz_alt,
]

np.sum(loops)

-19.906517094017097

In [79]:
loops = [
    cz,

    cx*(-1/ax)*az,

    cy*(-1/by_new)*bz_new,

    cx*(-1/ax)*ay*(-1/by_new)*bz_new
]

np.sum(loops)

6.013698630136986

In [67]:
by_new = by
bz_new = bz
new_term = cx/(-bx)*bz
cz + cx/(-ax)*ay/(-by_new)*bz_new + cx/(-ax)*az + cy/(-1*by_new)*bz_new + new_term

32.17132867132867

In [76]:
my_list = [
    # going up to x
    cx*(-1/ax)*az,
    cx*(-1/ax)*ay*(-1/by)*bz,
    cx*(-1/bx)*bz,

    cy*(-1/by)*bx*(-1/ax)*az,
    cy*(-1/by)*bx*(-1/ax)*ay*(-1/by)*bz,
    cy*(-1/by)*bx*(-1/bx)*bz,

    #going up to a
    cy*(-1/ay)*az
    cy*(-1/ay)*ay*(-1/by)*bz,



    cy*(-1/by)*bz,
    cy*(-1/by)*bx*(-1/ax)*az,
    cy*(-1/by)*bx*(-1/ax)*ay*(-1/by)*bz,
    cy*(-1/ay)*az,
    cy*(-1/ay)*ax*(-1/bx)*bz,
    cz,

]
np.sum(my_list)

35.9278095641732

In [75]:
my_list

[12.75,
 1.8409090909090908,
 -0.6923076923076923,
 0.2727272727272727,
 5.022727272727273,
 -1.8888888888888888,
 -0.10256410256410257,
 18]

In [51]:
cz - (cy/by)*bz - (cx/ax)*az - (cx/bx)*bz + (cx*ay)/(ax*by)*bz

32.17132867132867

In [52]:
(cx*ay)/(ax*by)*bz

1.8409090909090908

(18, -0.2727272727272727, -12.75, 0.6923076923076923, 1.8409090909090908)

In [15]:
from sympy import *
m = Matrix(M)
M_rref = m.rref()
M_rref

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [19]:
import numpy as np
# Function to check if matrix is in REF

def is_row_echelon_form(matrix):
	if not matrix.any():
		return False

	rows = matrix.shape[0]
	cols = matrix.shape[1]
	prev_leading_col = -1

	for row in range(rows):
		leading_col_found = False
		for col in range(cols):
			if matrix[row, col] != 0:
				if col <= prev_leading_col:
					return False
				prev_leading_col = col
				leading_col_found = True
				break
		if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
			return False
	return True

def find_nonzero_row(matrix, pivot_row, col):
	nrows = matrix.shape[0]
	for row in range(pivot_row, nrows):
		if matrix[row, col] != 0:
			return row
	return None

# Swapping rows so that we can have our non zero row on the top of the matrix
def swap_rows(matrix, row1, row2):
	matrix[[row1, row2]] = matrix[[row2, row1]]

def make_pivot_one(matrix, pivot_row, col):
	pivot_element = matrix[pivot_row, col]
	matrix[pivot_row] //= pivot_element
	# print(pivot_element)

def eliminate_below(matrix, pivot_row, col):
	nrows = matrix.shape[0]
	pivot_element = matrix[pivot_row, col]
	for row in range(pivot_row + 1, nrows):
		factor = matrix[row, col]
		matrix[row] -= factor * matrix[pivot_row]

# Implementing above functions
def row_echelon_form(matrix):
	nrows = matrix.shape[0]
	ncols = matrix.shape[1]
	pivot_row = 0
# this will run for number of column times. If matrix has 3 columns this loop will run for 3 times
	for col in range(ncols):
		nonzero_row = find_nonzero_row(matrix, pivot_row, col)
		if nonzero_row is not None:
			swap_rows(matrix, pivot_row, nonzero_row)
			make_pivot_one(matrix, pivot_row, col)
			eliminate_below(matrix, pivot_row, col)
			pivot_row += 1
	return matrix


row_echelon_form(M)

array([[1, 2, 4],
       [0, 1, 3],
       [0, 0, 1]])

In [ ]:
np.linalg.det(M[:2,:2])

In [12]:
m1*m2

-73.0